### ISSUE TITLE
key

### ISSUE THREAD

**Issue by VB10** [suleymangunes/Cryptocurrency-ranking-app#2]
https://github.com/suleymangunes/Cryptocurrency-ranking-app/blob/9048204f43f322dfca99542e5638a34d83f1237a/lib/view/home/service/crypto_repository.dart#L14

saklaa ben geldim :) bu durumalrda bir class yapıp onu ignore koyup oradan static okuyaiblirisn basitçe

**Comment by workspace-cs** [comment]
Hoşgeldiniz Hocam. Hemen yaptım.
